### ISSUE TITLE
Study brain atlases, their region and data extraction for models

### ISSUE THREAD

**Issue by eroma2014** [gt-artisan/Neuroscience-Cybershuttle#1]
Study existing brain atlases and how the regions and data for regions are presented. Focus on extracting data to inject for models in the expected format. Before implementing CI for extraction and converting to the expected format, the atlases and regions have to be finalized for initial use cases. 

- [ ] Goal 1: [Review, finalize and document brain atlases to work on data extractions.](https://github.com/GT-ARTISAN/Neuroscience-Cybershuttle/issues/2) 
- [ ] Goal 2: [Finalize the regions, gain an understanding of existing data in brain atlases and how to extract and data formats to convert them](https://github.com/GT-ARTISAN/Neuroscience-Cybershuttle/issues/3)
- [ ] Goal 3: [Manually extract regional information from brain atlases to implement ion channel expressions for the whole brain based on existing brain models.](https://github.com/GT-ARTISAN/Neuroscience-Cybershuttle/issues/4)
