### ISSUE TITLE
Implement improving the parameter sweeping through Jupyter notebooks 

### ISSUE THREAD

**Issue by eroma2014** [gt-artisan/Neuroscience-Cybershuttle#10]
- [ ] Goal 1: [Release the existing Python notebook packaged in a self-contained environment with easy installation for users. ](https://github.com/GT-ARTISAN/Neuroscience-Cybershuttle/issues/11)
- [ ] Goal 2: [Jupyter notebook to seamlessly compute on different HPC resources. ](https://github.com/GT-ARTISAN/Neuroscience-Cybershuttle/issues/12)
- [ ] Goal 3: [Improve the user experience with the notebook.](https://github.com/GT-ARTISAN/Neuroscience-Cybershuttle/issues/13)
